### ISSUE TITLE
Websites

### ISSUE THREAD

**Issue by korakoe** [samuelcolvin/dnserver#1]
I used your code, and the server works, but websites dont load

**Comment by samuelcolvin** [comment]
Which website?

**Comment by korakoe** [comment]
any, no domains work

Edit: it does grab the IP, however in a browser it just hangs

**Comment by samuelcolvin** [comment]
I can't help I'm afraid, I haven't used this code for years. You'll have to investigate yourself.

**Comment by korakoe** [comment]
no problem
