### ISSUE TITLE
Question? What's can you give examples of the use case for this?

### ISSUE THREAD

**Issue by Tomperez98** [samuelcolvin/dnserver#11]

**Comment by samuelcolvin** [comment]
I'm not sure what your question is, please provide an issue body with details.

**Comment by samuelcolvin** [comment]
no answer, feel free to reply here if you'd like to clarify the question.

**Comment by samuelcolvin** [comment]
At a guess of what you're asking:

I built this when I was developing a service that queried DNS records (`CNAME`, `TXT`, `SPF`) like email services do, I wanted a way to configure and run a DNS server locally.

But you can use this for whatever you want as long as you don't need high performance, scalability.
