### ISSUE TITLE
Update zones while the server is running

### ISSUE THREAD

**Issue by azmeuk** [samuelcolvin/dnserver#14]
I use dnserver in addition to [pytest-httpserver](https://github.com/csernazs/pytest-httpserver) to build a full fake network environment for unit tests.

pytest-httpserver can open a httpserver on a random port, and has utilities to control the server response within the unit tests, which is very convenient:

```python
def test_my_client(httpserver):
    httpserver.expect_request("/foobar").respond_with_json({"foo": "bar"})
    assert requests.get(httpserver.url_for("/foobar")).json() == {"foo": "bar"}
```

---

I a unit test scenario, suppose I want to run a DNS SRV request to get the hostname and the port for a given service (for instance caldav), then simulate that service with pytest-httpserver.

I would
- need to choose a port and write it in a fixture toml zone file
- hope that the port will be free at the moment the test will be ran
- run a test httpserver that will listen to that specific port

Having to rely on the port being free at the moment the test is running is far from ideal. Manually setting a port for a pytest-httpserver is quite cumbersome and makes you write a lot of fixtures.

For those reasons I think having a way to dynamically set the DNS responses while the server is running (in fixtures or directly in unit tests) would be great. I dream of something like this:

```python
async def test_caldav(dnserver, httpserver):
    dnserver.add_zone(host='caldav.example.com', type='A', answer='127.0.0.1')
    dnserver.add_zone(host='_caldav._tcp.example.com', type='SRV', answer=[0, 1, httpserver.port, 'caldav.example.com.'])

    httpserver.expect_request("/").respond_with_data("some caldav response")

    resolver_kwargs = dict(nameservers=[dnserver.host], tcp_port=dnserver.port, udp_port=dnserver.port)
    http_resolver = aiohttp.resolver.AsyncResolver(**resolver_kwargs)
    dns_resolver = aiodns.DNSResolver(**resolver_kwargs)

    dns_answer = dns_resolver.query(f"_caldav._tcp.example.com", "SRV")
    caldav_url = f"http://{dns_answer[0].host}:{dns_answer[0].port}"

    connector = aiohttp.TCPConnector(resolver=http_resolver)
    async with aiohttp.ClientSession(connector=connector) as session:
        async with session.get(caldav_url) as result:
            assert (await result.text()) == "some caldav response"
```

Though some of this might be out of scope for dnserver and better suited in a *pytest-dnserver* package.

Any thoughts?

**Comment by azmeuk** [comment]
For the record, here is my current dnserver pytest fixture.

```python
@pytest.fixture
def dns_server(request):
    """
    Local DNS server.
    The DNS servers tries to load a zone file at 'tests/fixtures/{test_name}.toml'
    if it exists, else 'tests/fixtures/default_zones.toml'.
    Then it renders the file with jinja2 so test fixtures are available as variables
    inside the zones file. This allows to dynamically use port and hosts inside the
    zones file.
    """

    import tempfile
    from jinja2 import Template
    from dnserver import DNSServer

    test_name = request.node.name
    test_fixtures = {
        fixture_name: request.getfixturevalue(fixture_name)
        for fixture_name in request.fixturenames
        if fixture_name != "dns_server"
    }

    zones_filename = (
        test_name if os.path.exists(f"tests/fixtures/{test_name}.toml") else "default_zones"
    )

    with open(f"tests/fixtures/{zones_filename}.toml") as fd:
        template = Template(fd.read())
        zone = template.render(**test_fixtures)

    with tempfile.NamedTemporaryFile() as fd:
        fd.write(zone.encode())
        fd.flush()
        server = DNSServer(zones_file=fd.name, port=DNS_PORT, upstream=None)
        server.start()

    yield server
    server.stop()
```

I automatically loads a zone file that has the same name than the test function. I could reach some level of *dynamic port* by using jinja variables inside the zones file:

```
[[zones]]
host = '_caldavs._tcp.example.com'
type = 'SRV'
answer = [0, 1, {{ httpsserver.port }}, 'caldav.example.com']
```

This works well, but the main drawback of this is that I have to run a different dnserver for each test to have a test specific configuration. This makes test time a bit long.

**Comment by samuelcolvin** [comment]
PR welcome to move the toml parsing logic out of `DnsServer`, then instead of writing a toml file, you could just create `Records`.

I think there's nothing to stop you editing records/zones while the server is running.
