### ISSUE TITLE
Release on pypi

### ISSUE THREAD

**Issue by azmeuk** [samuelcolvin/dnserver#3]
Once (an if) #2 is merged, this would be awesome to release the project on pypi so the `DNSServer` class could be used in other projects unit tests.

What do you think?

**Comment by samuelcolvin** [comment]
Fine by me, see my comment on #2

**Comment by samuelcolvin** [comment]
Done https://pypi.org/project/dnserver/

**Comment by azmeuk** [comment]
Wow that was quick! Thank you very much.
