### ISSUE TITLE
Let upstream be `None`

### ISSUE THREAD

**Issue by azmeuk** [samuelcolvin/dnserver#8]
Hi. Thank you again for your amazing work!

I can now use dnserver in unit tests :rocket:

```python
@pytest.fixture(scope="session")
def dns_server():
    from dnserver import DNSServer

    server = DNSServer(
        zones_file="tests/fixtures/zones.toml", port=DNS_PORT, upstream=None
    )
    server.start()
    yield server
    server.stop()
```
However I would like to be able to disable any upstream DNS server, so my unit tests won't make any network I/O. At the moment this is prevented by this line:

https://github.com/samuelcolvin/dnserver/blob/ef85e97e5b80b0f031fa4f1bedf90440339eb800/dnserver/main.py#L125

What do you think?

**Comment by samuelcolvin** [comment]
Well, it's also prevented by other logic, if you set `self.upstream = None`, there are errors.

PR welcome, you probably want to change

https://github.com/samuelcolvin/dnserver/blob/ef85e97e5b80b0f031fa4f1bedf90440339eb800/dnserver/main.py#L115-L116

Default should still be to use `1.1.1.1`.
